### ISSUE TITLE
Can't create a PNG using the command or the scripts provided in examples

### ISSUE THREAD

**Issue by tonix-tuft** [mamor/phantom-chart-to-png#1]
When I try to render a Chart JS or Google chart using phantomjs on the command line or using the PHP example you provided:

`
phantomjs chartjs.coffee chartjs.png 600 400 line '{"labels":["January","February","March","April","May","June","July"],"datasets":[{"fillColor":"rgba(220, 220, 220, 0.5)","strokeColor":"rgba(220, 220, 220, 1)","pointColor":"rgba(220, 220, 220, 1)","pointStrokeColor":"#fff","data":[65,59,90,81,56,55,40]},{"fillColor":"rgba(151, 187, 205, 0.5)","strokeColor":"rgba(151, 187, 205, 1)","pointColor":"rgba(151, 187, 205, 1)","pointStrokeColor":"#fff","data":[28,48,40,19,96,27,100]}]}' '{"scaleLineWidth":"5"}'
`

I get the following error:

`TypeError: undefined is not a constructor (evaluating 'extensions[ext](this, this.filename)')
_load@phantomjs://platform/bootstrap.js:278:24
require@phantomjs://platform/bootstrap.js:311:21
require@phantomjs://platform/bootstrap.js:263:32
global code@phantomjs://code/script.js:7:12`

I am using OS X El Capitan, phantomJS installed as an NPM module as you said in the README file.

How can I fix it?

**Comment by mamor** [comment]
thx! I fixed it. https://github.com/mamor/phantom-chart-to-png/commit/87aac7d35a669baf627e4ea7c14508679b2ffcc8

**Comment by tonix-tuft** [comment]
Thanks, now it works. But it seems to have problems with doughnut, pie and radar charts (the created PNGs are empty), if I try to execute:

```
#!/usr/bin/env php
<?php
$dest = 'chartjs-example.php.png';
$width = 600;
$height = 600;
$type = 'pie';
$data = [
			    'labels' => [
							 "Red",
							 "Blue",
							 "Yellow"
							 ],
				 'datasets'=> [
  [
  'data' => [300, 50, 100],
  'backgroundColor'=> [
						  "#FF6384",
						  "#36A2EB",
						  "#FFCE56"
						  ],
  'hoverBackgroundColor'=> [
								 "#FF6384",
								 "#36A2EB",
								 "#FFCE56"
								 ]
  ]]
];

$opts = ['animation' => false];
$format = "/usr/local/bin/phantomjs ../chartjs.js %s %s %s %s '%s' '%s'";
$command = sprintf($format, $dest, $width, $height, $type, json_encode($data), json_encode($opts));
exec($command);
```

An empty PNG is created.

**Comment by mamor** [comment]
fixed. https://github.com/mamor/phantom-chart-to-png/commit/eb56a1a1df3d46a59873cfc397dfada6f3e0aea7

you must run "npm install", and options changed, see readme.

**Comment by tonix-tuft** [comment]
Thanks! Now everything works fine.
